### ISSUE TITLE
Bot Speed

### ISSUE THREAD

**Issue by GreyMatter658** [PredatorHackerzZ/TG-YouTube-Uploader#1]
It works on every single command and it also completes every single command but the only issue is its too slow.

**Comment by PredatorHackerzZ** [comment]
Use DC4  Bots bro

**Comment by GreyMatter658** [comment]
🙄i am noob now what is DC4 bots? Can you please tell me

**Comment by PredatorHackerzZ** [comment]
Uk Ph No.. Based telegram account

**Comment by GreyMatter658** [comment]
Oooo is it thank you so much bro🙏 i will test it now

**Comment by GreyMatter658** [comment]
Bro i tried with a Telegram account on UK number but still no difference🤷
